title: Shanthar Rajinth
logo: /assets/img/profilepicsmall.png
description: rajinthss@eng.pdn.ac.lk
show_downloads: false
google_analytics: UA-215543120-1
theme: jekyll-theme-minimal
future: true
timezone: Asia/Colombo
